version: "3.9"

services:
  db:
    container_name: db_container
    image: mariadb:10.7.3-focal
    restart: always
    environment:
      MARIADB_USER: 'admin'
      MARIADB_PASSWORD: 'admin'
      MARIADB_ROOT_PASSWORD: 'root'

  phpmyadmin:
    container_name: pma_container
    image: phpmyadmin:5.1.3-apache
    environment:
      MARIADB_USER: 'admin'
      MARIADB_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'root'
#    volumes:
#      - ./demo_data:/docker-entrypoint-initdb.d
    ports:
      - "8181:80"

  server:
    container_name: http_container
    image: httpd:2.4.53-alpine3.15
    ports:
      - "8180:80"
#networks:
#  postgres:
#    driver: bridge
